
import com.android.build.api.artifact.SingleArtifact
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.gradle.api.tasks.Copy
import java.io.FileInputStream
import java.util.Properties

plugins {
	alias(libs.plugins.android.application)
	alias(libs.plugins.devtools.ksp)
	alias(libs.plugins.hilt.android)
}

apply(from = rootProject.file("app/PXTasks.gradle.kts"))

val generatedLicenseResources = layout.buildDirectory.dir("generated/licenseResources")
val copyProjectLicense = tasks.register<Copy>("copyProjectLicense") {
	from(rootProject.file("LICENSE"))
	rename { "PixelXpert-GPL-3.0.txt" }
	into(generatedLicenseResources.map { it.dir("META-INF/licenses") })
}

kotlin {
	compilerOptions {
		jvmTarget = JvmTarget.JVM_17
	}
}

android {
	namespace = "com.tsinbei.pixelxpert"
	compileSdk = 36

	defaultConfig {
		applicationId = "com.tsinbei.pixelxpert"
		minSdk = 36
		targetSdk = 36
		versionCode = getVersionCode()
		versionName = "AutoGeneratedLater"
		ndk {
			//noinspection ChromeOsAbiSupport
			abiFilters.add("arm64-v8a")
		}
	}

	val keystorePropertiesFile = rootProject.file("ReleaseKey.properties")
	var releaseSigning = signingConfigs.getByName("debug")

	try {
		val keystoreProperties = Properties().apply {
			if (keystorePropertiesFile.exists()) {
				FileInputStream(keystorePropertiesFile).use(::load)
			} else {
				setProperty("keyAlias", System.getenv("PIXELXPERT_KEY_ALIAS"))
				setProperty("keyPassword", System.getenv("PIXELXPERT_KEY_PASSWORD"))
				setProperty("storeFile", System.getenv("PIXELXPERT_STORE_FILE"))
				setProperty("storePassword", System.getenv("PIXELXPERT_STORE_PASSWORD"))
			}
		}

		releaseSigning = signingConfigs.create("release") {
			keyAlias = keystoreProperties.getProperty("keyAlias")
			keyPassword = keystoreProperties.getProperty("keyPassword")
			storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
			storePassword = keystoreProperties.getProperty("storePassword")
		}
	} catch (_: Exception) {
	}

	buildTypes {
		release {
			isMinifyEnabled = true
			isShrinkResources = true
			proguardFiles("proguard-android-optimize.txt", "proguard.pro", "proguard-rules.pro")
			signingConfig = releaseSigning
		}
		debug {
			isDebuggable = true
			isMinifyEnabled = false
			isShrinkResources = false
			signingConfig = releaseSigning
		}
	}

	buildFeatures{
		viewBinding = true
		buildConfig = true
		aidl = true
	}

	sourceSets.getByName("main") {
		resources.srcDir("build/generated/licenseResources")
	}

	compileOptions {
		isCoreLibraryDesugaringEnabled = true

		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	packaging {
		jniLibs.excludes += setOf(
			"**/libpytorch_jni_lite.so"
		)
	}
}

tasks.configureEach {
	if (name.startsWith("process") && name.endsWith("JavaRes")) {
		dependsOn(copyProjectLicense)
	}
}

androidComponents {
	val apkName = "PixelXpert.apk"
	onVariants { variant ->
		val artifactDir = variant.artifacts.get(SingleArtifact.APK)

		val versionName = getVersionName()

		variant.outputs.forEach { output ->
			output.versionName.set(versionName)
		}

		tasks.named("preBuild").get().doLast {

			try {
				artifactDir.get().asFile.listFiles()
					.filter { it.name.equals(apkName) }
					.forEach {
						it.delete()
					}
			} catch (_ : Throwable){}
		}

		tasks.whenTaskAdded {
			if (name.lowercase() == "assemble${variant.name.lowercase()}")
			{
				doLast {
					artifactDir.get().asFile.listFiles()
						.filter { it.extension == "apk" }
						.forEach {
							if (it.exists() && !it.name.equals(apkName)) {
								it.renameTo(File(it.parent, apkName))
							}
						}
				}
			}
		}
	}
}

dependencies {
	implementation(project(":annotations"))
	annotationProcessor(project(":annotationProcessor"))
	coreLibraryDesugaring(libs.desugar.jdk.libs)

	compileOnly(files("lib/api-82.jar"))
	compileOnly(files("lib/api-82-sources.jar"))

	implementation(project(":Submodules:RangeSliderPreference"))

	implementation (libs.androidx.constraintlayout)
	implementation (libs.androidx.navigation.fragment.ktx)
	implementation (libs.androidx.navigation.ui.ktx)
	implementation (libs.androidx.fragment.ktx)
	implementation (libs.androidx.appcompat)
	implementation (libs.androidx.annotation)
	implementation (libs.androidx.preference.ktx)
	implementation (libs.androidx.recyclerview)
	implementation (libs.android.material)
	implementation (libs.androidx.ui.geometry)
	//noinspection KtxExtensionAvailable
	implementation (libs.androidx.activity)
	implementation (libs.androidx.work.runtime)
	implementation (libs.androidx.concurrent.futures)
	implementation (libs.androidx.transition)

	// The core module that provides APIs to a shell
	implementation (libs.libsuCore)
	// Optional: APIs for creating root services. Depends on ":core"
	implementation (libs.libsuService)
	// Optional: Provides remote file system support
	implementation (libs.libsuNIO)

	implementation (libs.remotepreferences)
	// Remote Preferences for Xposed Module prefs
	implementation (libs.colorpicker) //Color Picker Component for UI
	implementation (libs.persian.date.time) //Persian Calendar

//	implementation (libs.markdown) //Markdown reader

	// Search Preference
	implementation (libs.androidx.cardview)
	implementation (libs.apache.commons.text)

	implementation (libs.androidx.swiperefreshlayout)

	// Class initializer
	// https://mvnrepository.com/artifact/org.objenesis/objenesis
	implementation (libs.objenesis)

	implementation (libs.ntpClient) //NTP Client

	//Google Subject Segmentation - MLKit
	implementation (libs.play.services.mlkit.subject.segmentation)
	implementation (libs.play.services.base)

	// Splash screen
	implementation (libs.androidx.core.splashscreen)

	// Lottie
	implementation(libs.lottie)

	implementation (libs.prdownloader)

	implementation (libs.pytorch.android.lite)
	implementation (libs.pytorch.android.torchvision.lite)
	implementation (libs.gson)

	implementation(libs.androidx.ui)
	implementation(libs.androidx.localbroadcastmanager)

	implementation(libs.hilt.android)
	ksp(libs.hilt.android.compiler)

	compileOnly(libs.lsposed.api)
	implementation(libs.lsposed.service)
	implementation(libs.dexkit)

	//mark-down view for changelog
	implementation(libs.markdownview.android)
}
