name: Make Xposed Test Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Grab source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Setup JDK 21
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '21'
          distribution: 'jetbrains'
          cache: gradle

      - name: Grant permission shell scripts
        run: chmod +x .github/*.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK

        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.0"
          
      - name: Magisk Module Generation
        run: .github/make_debug_zip.sh

      - name: Upload APK file
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PixelXpert_Xposed.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
        
      - name: Upload Xposed Artifact to Actions
        uses: actions/upload-artifact@v7.0.1
        with: 
          name: PixelXpert_Xposed.zip
          path: output
